services:
  redis:
    restart: unless-stopped
    image: redis
    ports:
      - 6379:6379

  simpleweb:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 3001:3000
    depends_on:
      - redis
